name: poko_agent
description: "PokéAgents - AI-powered Pokémon-inspired NFT agents on Base blockchain"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  dio: ^5.4.3
  web3dart: ^2.7.3
  walletconnect_flutter_v2: ^2.3.12
  lottie: ^3.1.0
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  http: ^1.2.1
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10
  intl: ^0.19.0
  url_launcher: ^6.2.6
  cached_network_image: ^3.3.1
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  flutter_tts: ^4.0.2
  confetti: ^0.7.0
  shimmer: ^3.0.0
  badges: ^3.1.2
  fl_chart: ^0.68.0
  uuid: ^4.4.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/login_character.png
    - assets/images/google_icon.png
    - assets/images/signup_character.png
    - assets/images/Welcome.png
    - assets/images/mint.png
    - assets/animations/


  fonts:
    - family: PokemonSolid # This is the name you'll use in your code
      fonts:
        - asset: fonts/Pokemon Solid.ttf # Path to your font file
